name: Upload to GCS

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Upload file to GCS
      run: |
        gsutil cp ${{ github.workspace }}/index.html gs://${{ secrets.GCS_BUCKET_NAME }}
      env:
        GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}

    - name: Clean up
      run: |
        rm -rf ${{ github.workspace }}/index.html

