on:
  push:
    branches:
    - main
    paths:
    - index.html
  workflow_dispatch:

name: Upload to GCS

env:
  BUCKET_NAME: imjohnbo-gcp-demo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #Checks-out your repo under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
      with:
        version: latest
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        service_Account_email: ${{ secrets.GCP_SA_EMAIL }}
        export_default_credentials: true

    - uses: GoogleCloudPlatform/github-actions/upload-cloud-storage@0.1.3
      with:
        path: index.html
        destination: ${{ env.BUCKET_NAME }}